### ISSUE TITLE
Timeout on waitForConnection(Transport)

### ISSUE THREAD

**Issue by arthurdeschamps** [ctron/kapua-gateway-client#1]
The method `waitForConnection` of Transport could use a timeout mechanism.

**Comment by ctron** [comment]
This is a reasonable request for enhancement.

There will be a discussion around eclipse/kapua#701 in the next few days if the client SDK will be merged into https://github.com/eclipse/kapua or not. If this turns out to be a lengthy discussion then I will make the change here. Otherwise I would like to wait a bit longer and add this in the Kapua repository.

**Comment by ctron** [comment]
This is closed by eclipse/kapua@35d288db947e3dd85a207ac23d9a451683e90e74
